### PR TITLE
fix pecl/pear providers query method

### LINKED ISSUE #255: deep_merge of php::extensions does not work with versions
If you want to install a specific PECL version and declare it in Hiera as a hash, the behavior is unexpected and wrong:

Consider the following hiera excerpt:

php::extensions:
  imagick:
    provider: pecl
    ensure: 3.4.3RC1
  redis:
    provider: pecl
    ensure: 2.2.8
  mongo:
    provider: pecl
    ensure: 1.6.14

It ends up in wrong (merged) versions:
Error: Could not update: Execution of '/usr/bin/pecl upgrade -f imagick-2.2.8' returned 1: WARNING: failed to download pecl.php.net/imagick-3.4.3RC1, additionally the suggested version (3.4.3RC1) is the same as the locally installed one.
upgrade failed
Wrapped exception:
Execution of '/usr/bin/pecl upgrade -f imagick-2.2.8' returned 1: WARNING: failed to download pecl.php.net/imagick-3.4.3RC1, additionally the suggested version (3.4.3RC1) is the same as the locally installed one.
upgrade failed
Error: /Stage[main]/Php/Php::Extension[redis]/Package[pecl-redis]/ensure: change from 3.4.3RC1 to 2.2.8 failed: Could not update: Execution of '/usr/bin/pecl upgrade -f imagick-2.2.8' returned 1: WARNING: failed to download pecl.php.net/imagick-3.4.3RC1, additionally the suggested version (3.4.3RC1) is the same as the locally installed one.
upgrade failed

For some reason the pecl package provider picks the version kind of randomly.

### PR DESCRIPTION
**Pull request by cbaoxa**
could return info about another package

example:
```
  pry> @resource
  => Package[pecl-mongo]
  pry> self.class.pecllist(justme: peclname)
  => {:name=>"pecl-apcu", :ensure=>"4.0.7", :provider=>:peclcmd}
```

this wrongly results in pecl-mongo not being installed when needed

fixes #255 as well by returning the correct version for installed
packages

### CODE REVIEW

**Comment by igalic** [comment]
@cbaoxa would you mind adding a spec test for this so we can maybe learn from our horrible mistakes of the past?

**Comment by cbaoxa** [comment]
@igalic sure, working on it, plus maybe merging all the features in the pear provider, as it can handle both pear and pecl extensions

File: spec/fixtures/unit/provider/package/pear/list_a [hunk 1]
```diff
@@ -0,0 +1,22 @@
+[1mInstalled packages, channel __uri:[m
+==================================
+(no packages installed)
+
+[1mInstalled packages, channel doc.php.net:[m
+========================================
+(no packages installed)
+
+[1mInstalled packages, channel pear.php.net:[m
```
Comment (igalic) [inline spec/fixtures/unit/provider/package/pear/list_a]: is it not possible to get this lists without those ansi characters?

File: lib/puppet/provider/package/pear.rb [hunk 2]
```diff
@@ -2,107 +2,98 @@
...
   has_feature :upgradeable
   has_feature :install_options
 
-  case Facter.value(:operatingsystem)
-  when 'Solaris'
-    commands pearcmd: '/opt/coolstack/php5/bin/pear'
-  else
-    commands pearcmd: 'pear'
-  end
+  commands pearcmd: 'pear'
```
Comment (igalic) [inline lib/puppet/provider/package/pear.rb]: i'd just call this `pear`… you can maybe add a wrapper with default options that you call `pearcmd` (or vice versa?)

**Comment by igalic** [comment]
@bastelfreak is there any way to fix the 1.9 failures, or can we just gracefully ignore them for now?

File: spec/fixtures/unit/provider/package/pear/list_a (hunk 1 above)
Comment (cbaoxa) [inline spec/fixtures/unit/provider/package/pear/list_a]: Not directly with pear arguments, but it is with ENV['TERM']='dumb'

**Comment by cbaoxa** [comment]
PR updated wrt @igalic comments.
1.9 failures are related to beaker dependencies, but the module is running fine on my test env (ruby 1.9.3, puppet 3.8.7)

**Comment by igalic** [comment]
thank you so much @cbaoxa \o/
